"""Generate or check the prepared TypeScript schema DATA from this checkout.

Run with the project's locked Python environment. No device, catalogue or solver
is constructed; caller-specific StructuredSchema records use the Python API.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from solarlab.config.schema import export_configuration_schema  # noqa: E402

DEFAULT_OUTPUT = ROOT / "web/src/generated/configuration-schema.ts"


def render() -> bytes:
    document = json.dumps(export_configuration_schema(), indent=2,
                          sort_keys=True, ensure_ascii=True, allow_nan=False)
    return (
        "// Generated by scripts/generate_configuration_schema.py; do not edit.\n"
        "// DATA only: this typeof is not an Input/Resolved/Result wire type.\n"
        "// Each schema owns its $defs/$ref scope; backend validators are authoritative.\n"
        "// StructuredSchema metadata is caller-supplied through the Python API.\n"
        f"export const configurationSchema = {document} as const;\n\n"
        "export type ConfigurationSchemaMetadata = typeof configurationSchema;\n"
    ).encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if output is absent or differs; never write")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        if not args.output.is_file() or args.output.read_bytes() != expected:
            print(f"stale or missing configuration schema: {args.output}",
                  file=sys.stderr)
            return 1
        print(f"configuration schema is current: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(expected)
    print(f"generated configuration schema: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
